$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: fraud-env

conda_file:
  channels:
    - conda-forge
  dependencies:
    - python=3.11
    - pip
    - pip:
        - azureml-inference-server-http
        - -r requirements-prod.txt